// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QueueSafe.Entities;

namespace QueueSafe.Api.Migrations
{
    [DbContext(typeof(QueueSafeContext))]
    partial class QueueSafeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("QueueSafe.Entities.Address", b =>
                {
                    b.Property<int>("Postal")
                        .HasColumnType("int");

                    b.Property<string>("StreetName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("HouseNumber")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("Postal", "StreetName", "HouseNumber");

                    b.HasIndex("StoreId")
                        .IsUnique();

                    b.ToTable("Address");
                });

            modelBuilder.Entity("QueueSafe.Entities.Booking", b =>
                {
                    b.Property<string>("Token")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Token");

                    b.HasIndex("StoreId");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("QueueSafe.Entities.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Store");
                });

            modelBuilder.Entity("QueueSafe.Entities.Address", b =>
                {
                    b.HasOne("QueueSafe.Entities.Store", "Store")
                        .WithOne("Address")
                        .HasForeignKey("QueueSafe.Entities.Address", "StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("QueueSafe.Entities.Booking", b =>
                {
                    b.HasOne("QueueSafe.Entities.Store", "Store")
                        .WithMany("Bookings")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("QueueSafe.Entities.Store", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
